### ISSUE TITLE
Getting latest build (snapshot / edge)

### ISSUE THREAD

**Issue by captainhorsepower** [EventStore/EventStoreDB-Client-Java#68]
Hi! I'd like to use lates build (based on trunk branch). But I don't see how I can download that and use as maven dependency.

Specifically, I want to use `EventDataBuilder#json` as from pr #64 , but that's not on maven central yet. 

Currently I build locally and do `./gradlew publishToMavenLocal`, but do want to setup CI pipeline and don't want tricky workarounds to make it work there.

I've seen that you already publish snapshot builds to github pakcages ( pr #23 ), so how can add that to my `pom.xml`?

**Comment by YoEight** [comment]
Hi @captainhorsepower, this is definitely something we should add. I'm looking into adding snapshot on Maven Central.

**Comment by YoEight** [comment]
I published today's trunk snapshot branch on Maven Central, I don't know how long it takes for the rest of the world to see that version available (version is `1.0.1-SNAPSHOT`. When pushing a 'real' release, it usually takes 2-3 hours.

**Comment by captainhorsepower** [comment]
Thank you, @YoEight. Will let you know once I can access. BTW, are you going publish this snapshot builds automatically with every merged pull-request or manually / on demand?

**Comment by YoEight** [comment]
It will be set automatically when merging on the main branch. See the pending PR #72

**Comment by captainhorsepower** [comment]
Still can't see that on maven-central, nor find with gradle.  Is there a dedicated 'snaphsts repo'?

![Screen Shot 2021-04-27 at 12 21 32 PM](https://user-images.githubusercontent.com/35666863/116218559-511e5a80-a753-11eb-967b-bdea3873a1cd.png)

**Comment by YoEight** [comment]
I see those snapshots there: https://oss.sonatype.org/content/repositories/snapshots/com/eventstore/db-client-java/

**Comment by captainhorsepower** [comment]
Nice, I've configured repositories and now it works perfectly!

```groovy
repositories {
    mavenCentral()
    maven {
        url uri('https://oss.sonatype.org/content/repositories/snapshots')
    }
}
```

Gradle dynamic version also works: `api 'com.eventstore:db-client-java:1.0.+'` resolved to `com.eventstore:db-client-java:1.0.2-SNAPSHOT`

**Comment by dhirajkumar94** [comment]
@YoEight I can't find com.eventstore:db-client-java:1.0.2-SNAPSHOT in maven repository

**Comment by captainhorsepower** [comment]
> @YoEight I can't find com.eventstore:db-client-java:1.0.2-SNAPSHOT in maven repository

@dhirajkumar94 you need to add sonatype snapshots  to repositories in your `build.gradle` (or plugin) / `pom.xml`

**Comment by YoEight** [comment]
@dhirajkumar94 there is a section in the README file that explains how to do it: https://github.com/EventStore/EventStoreDB-Client-Java#snapshot-versions
