### ISSUE TITLE
Improve working with a large set of events

### ISSUE THREAD

**Issue by johanhaleby** [EventStore/EventStoreDB-Client-Java#70]
Hi again :)

From what I understand when reading the [documentation](https://developers.eventstore.com/clients/grpc/reading-events/reading-from-the-all-stream.html#reading-forwards), reading from the "$all" stream returns a `List<ResolvedEvent>`. But returning all events in the entire eventstore as a List would be highly inefficient and will most likely lead to OOM. The same docs says "This will return an AsyncEnumerable that can be iterated on", see image:

![image](https://user-images.githubusercontent.com/187029/115959788-3ad38d00-a50e-11eb-9301-d9de1b46d28f.png)

but this is cannot be true in Java right? At least I've never come across such a thing in Java yet :) 

Is there another way to read all events in the all stream? If so, maybe the docs should be updated to reflect this? 

I'm using version 1.0.0.

**Comment by YoEight** [comment]
It is not the case in Java indeed. All other clients have async streams/iterators though. Do you have any suggestion? The only solution I see is to use a callback instead (like we did when consuming a subscription).

**Comment by johanhaleby** [comment]
@YoEight The best way I know of for working with streams of data would be to expose something like a [reactive streams](https://www.reactive-streams.org/) compatible API (for example [projectreactor](https://projectreactor.io/)). But this is probably non-idiomatic for most Java devs and it would influence the entire API. So another option might be to either change the result of `result.getEvents()` from `List<ResolvedEvent>` to `Stream<ResolvedEvent>` (or add an additional method such as `result.getEventsAsStream()`). Under the covers you _can_ (but I'm not sure how difficult it is) create an instance of `Stream` that you populate with data asynchronously as they arrive. I think that Spring does something similar for MongoDB in the Spring Data MongoDB project. [StreamEx](https://github.com/amaembo/streamex) also allows you to push data to existing streams, which might be a useful trick to do under the covers?

**Comment by daMupfel** [comment]
I would be in favor of a reactive approach. Since GRPC already exposes its API in a reactive fashion (maybe at some point we get something like async/await for java). That seems to be what bigger frameworks are choosing as well (as mentioned above).

I don't know of a way to use java "Stream"s in an async/lazy fashion. I don't think that is natively supported.

**Comment by johanhaleby** [comment]
@daMupfel I mean, that it's possible to e.g. add values to a Stream from a different thread. For example, if you query for all events, `Stream<ResolvedEvent> stream = results.getEvents()`, then you could have the actual query happen in another thread that loads batches of data from the datastore. This data could then be appended to the stream as it arrives. 

Another, probably better option, that I have implemented myself so I know that this works well, is to generate a custom Stream (`Stream.generate(..)`) that holds state where it currently is in the stream of events (for example a "page" data structure containing skip and limit). So you can generate a nested stream, `Stream<Stream<ResolvedEvent>>`, that you internally flatMap so that the resulting type returned to the client is still `Stream<ResolvedEvent>`. The trick is to generate an infinite lazy stream but once the inner stream is completely consumed (in `Stream<Stream<ResolvedEvent>>`) you make a new call (internally) to fetch a new (inner) stream with the result of the next "page". You can combine this with a "takeUntil" condition so that user specified arguments are taken into account. For example, if the user wants to read from the `$all` stream with skip=30 and limit=600000, the implementation would chunk up the reads into multiple calls to the eventstore under the covers until all events matching "skip=30 and limit=600000" are returned or if there are no more events in the store.

**Comment by daMupfel** [comment]
True, that would probably work. Then the actual loading would happen somewhere else. But this still doesn't sound async to me, no? It does however solve the issue of not loading all documents at once (lazy). I think we are talking about slightly different things/use cases (nonblocking vs lazy batch loading) :).

I mean the thread who is resolving the Stream (like using forEach) will still block. There is no notion of a "Scheduler" in java Streams (that is what i mean :)).
Didn't actually know of Stream.generate(). so thanks for that :D 👍

**Comment by johanhaleby** [comment]
@daMupfel No there's no scheduler for Stream, you would have to spin off threads yourself. But you should probably ignore all that, my latest proposal is much better :)

**Comment by johanhaleby** [comment]
Having said that, using reactive streams would be much better since it also includes prefetch so that data is available (buffered) before you've completed a "page". With the streams approach, once the client has completed a single page, a new call would have to made to the DB, which will lead to the thread blocking and just sleeping waiting for IO. This will probably be improved with new JVM's though (project loom), but still.

**Comment by dpasek-senacor** [comment]
@johanhaleby We have now added a new PR in regard of supporting reative streams please take a look. Thoughts and feedback are welcome:
https://github.com/EventStore/EventStoreDB-Client-Java/pull/106

**Comment by YoEight** [comment]
Done by https://github.com/EventStore/EventStoreDB-Client-Java/pull/106
